Repository part3-4team-Taskify/Taskify, pull requests merged in 2025-04, with the labels that each got.

#124 [Feat] landing: 로그인 상태일 때 '대시보드 이동하기' 버튼으로 전환
  src/components/landing/Section1.tsx
  src/pages/mydashboard.tsx
Labels: Feat

#125 [Feat, Fix] Moal : 디자인 수정, 대시보드 삭제 확인 모달 추가 / 초대 모달 중복 문제 해결
  src/api/axiosInstance.ts
  src/components/modal/DeleteDashboardModal.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modal/NewDashboard.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/types/dashboard.ts
Labels: Fix, Feat

#123 [Feat] 모달 대시보드 생성
  package-lock.json
  package.json
  src/api/card.ts
  src/api/comment.ts
  src/api/userprofile.ts
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/CommentList.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/components/modalDashboard/formatDate.ts
  src/components/modalDashboard/profelicon.tsx
  src/components/modalInput/CardInput.tsx
  src/pages/_app.tsx
  src/pages/mypage.tsx
  src/types/cards.ts
  src/types/comments.ts
  src/types/task.ts
Labels: Feat

#126 [Style Fix] 사이드 메뉴, 마이대시보드 디자인 수정
  src/components/modalInput/ToDoModal.tsx
  src/components/sideMenu/SideMenu.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/mydashboard.tsx
Labels: Fix, Style

#127 [Feat] Modal: DeleteModal 컴포넌트 추가 / toast: 커스텀 토스트 추가 / 배포 에러 fix
  src/components/button/CardButton.tsx
  src/components/common/CustomToastContainer.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/MemberListMenu.tsx
  src/components/gnb/UserMenu.tsx
  src/components/input/Input.tsx
  src/components/modal/DeleteModal.tsx
  src/pages/_app.tsx
  src/pages/mydashboard.tsx
  src/styles/globals.css
Labels: Fix, Feat

#130 [Refactor] api 컨벤션 통일 / 배포 에러 fix 위해 teamId 하드코딩 제거
  src/api/apiRoutes.ts
  src/api/auth.ts
  src/api/card.ts
  src/api/changepassword.ts
  src/api/columns.ts
  src/api/comment.ts
  src/api/dashboards.ts
  src/api/members.ts
  src/api/sidemenu.ts
  src/api/userprofile.ts
  src/api/users.ts
  src/components/card/Profile.tsx
  src/components/columnCard/Column.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modal/NewDashboard.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/types/users.ts
Labels: Refector

#131 [Refactor] teamId 인자 제거
  src/components/columnCard/Column.tsx
Labels: Refector

#132 [Fix] 배포 에러 fix
  src/components/modal/DeleteDashboardModal.tsx
  src/components/modalDashboard/CardDetailModal.tsx
Labels: Fix

#129 [Fix] mypage: SideMenu 수정, 대시보드에서 카드 클릭시 모달창 나오게 설정
  src/api/card.ts
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/ToDoModal.tsx
  src/pages/mypage.tsx
  src/types/cards.ts
Labels: Fix

#136 [Test] 배포 환경에서 로그인 실패 에러 발생, 테스트용 코드 추가
  src/api/auth.ts
  src/pages/login.tsx
Labels: Fix

#137 [Fix] Update card.ts
  src/api/card.ts
Labels: Fix

#138 [Fix] CardType 이름 변경이 api 파일에 반영되지 않은 점 수정
  src/api/card.ts
Labels: Fix

#140 [Fix] base URL 수정
  src/api/auth.ts
  src/api/axiosInstance.ts
Labels: Fix

#141 [Feat Fix] 수정 모달 상태변경
  src/api/statusOptions.ts
  src/components/modalInput/StatusSelect.tsx
  src/components/modalInput/TaskModal.tsx
  src/components/sideMenu/SideMenu.tsx
Labels: Fix, Feat

#143 [Feat] Card: 무한스크롤 기능 추가, 카드 클릭 시 카드 상세모달 열림 기능 추가
  src/components/button/ColumnsButton.tsx
  src/components/button/TodoButton.tsx
  src/components/columnCard/Card.tsx
  src/components/columnCard/CardList.tsx
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/types/cards.ts
Labels: Style, Feat

#144 [Feat, Style] mypage: css & 반응형 수정, 정보 변경 시 toast 발생, toast 사라지면 새로고침 / Gnb: 멤버 목록 반응형 적용
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/common/CustomToastContainer.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/MemberListMenu.tsx
  src/components/gnb/MembersProfileIconList.tsx
  src/components/gnb/ProfileIcon.tsx
  src/components/input/Input.tsx
  src/components/table/member/MemberList.tsx
  src/pages/mypage.tsx
  src/styles/globals.css
Labels: Style, Feat

#145 [Style] Card: alert를 toast로 변경 Button: 커서 변경
  src/components/button/ColumnsButton.tsx
  src/components/button/TodoButton.tsx
  src/components/columnCard/Column.tsx
  src/components/common/CustomToastContainer.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style

#146 [Fix] vercel 오류 수정및 사이드메뉴, 나의 대쉬보드 수정
  src/api/statusOptions.ts
  src/components/modalInput/StatusSelect.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/mydashboard.tsx
Labels: Fix

#147 [Style] 카드 상세모달 스타일 수정
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/CardInput.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style

#148 [Fix] 버셀 오류 수정
  src/components/modal/NewDashboard.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/mydashboard.tsx
Labels: Fix

#149 [Fix] 대시보드 api 호출 에러 fix
  src/components/gnb/MembersProfileIconList.tsx
  src/components/gnb/ProfileIcon.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/NewDashboard.tsx
  src/components/table/member/RandomProfile.tsx
  src/pages/mydashboard.tsx
Labels: Fix

#150 [Fix] NewDashboard: 불필요한 코드 제거
  src/components/modal/NewDashboard.tsx
Labels: Fix

#152 [Fix] NewDashboard: 불필요한 코드 제거
  src/components/modal/NewDashboard.tsx
Labels: Fix

#151 [Feat] 카드 생성 후 새로고침 기능 추가
  src/api/axiosInstance.ts
  src/components/modalInput/ToDoModal.tsx
Labels: Feat

#153 [Style] 댓글리스트창 오른쪽버튼 크기 변경
  src/api/card.ts
  src/api/columns.ts
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/CommentList.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/components/modalInput/CardInput.tsx
  src/styles/globals.css
  src/types/task.ts
Labels: Style

#156 [Feat, Style] Modal: 카드 상세모달 삭제시 토스트알림 / Card: 프로필이미지 띄우기
  src/components/columnCard/Card.tsx
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetailModal.tsx
Labels: Style, Feat

#158 [Style, Refactor] mydashboard: 레이아웃 수정 / edit: 여백, 정렬 조정 / login: 전체 페이지 비로그인 접근 방지 적용
  src/components/modal/NewDashboard.tsx
  src/components/modalInput/ModalImage.tsx
  src/components/modalInput/ToDoModal.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/login.tsx
  src/pages/mydashboard.tsx
  src/pages/signup.tsx
Labels: Style, Refector

#160 [Fix, Refactor] 배포 에러 fix: 불필요한 코드 제거 / InvitedDashboard, ChangeBebridge: toast 소멸 후 새로고침 되도록 수정
  src/components/button/CardButton.tsx
  src/components/button/DashboardAddButton.tsx
  src/components/columnCard/Column.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/DeleteDashboardModal.tsx
  src/components/modal/DeleteMemberModal.tsx
  src/components/modal/NewDashboard.tsx
  src/components/modalInput/ModalImage.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Fix, Refector

#161 [Fix] 불필요한 타입 선언 제거
  src/components/button/DashboardAddButton.tsx
Labels: Fix

#163 [Refector]할 일 생성모달 z-index수정
  src/api/columns.ts
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Refector

#165 [Fix] CardDetailModal: 불필요한 코드 제거
  src/components/modalDashboard/CardDetailModal.tsx
Labels: Fix

#166 [Fix] 랜딩 시간 단축
  src/pages/index.tsx
Labels: Fix

#167 [Refactor] InviteDashboard: 초대 성공 시 모달 바로 닫히게 변경
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/common/CustomToastContainer.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/table/invited/InvitedDashBoard.tsx
Labels: Refector

#169 [Fix] 페이지별 사이드메뉴 갱신 추가
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mypage.tsx
Labels: Fix

#170 [Style] Gnb: MembersProfileIconList 텍스트 사이즈 반응형 변경
  src/components/gnb/MembersProfileIconList.tsx
Labels: Style

#171 [Fix] mypage: 모바일 환경에서 사이드메뉴 가로스크롤 현상 수정
  src/pages/mypage.tsx
Labels: Fix

#173 [Fix] mypage: 세로 스크롤 추가
  src/pages/mypage.tsx
Labels: Fix

#174 [Style] edit: 모바일 레이아웃 깨짐, 패딩 값 조절
  src/pages/dashboard/[dashboardId]/edit.tsx
Labels: Style

#175 [Refactor] 초대 성공 시 새로고침 기능 제거
  src/components/modal/InviteDashboard.tsx
Labels: Refector

#176 [Fix] 비밀번호 불일치 시에도 회원가입 성공 에러 수정
  src/pages/signup.tsx
Labels: Fix

#177 [Fix, Refactor] Profile: 이미지 업로드 제한 용량 초과 시 에러 처리 / Input: Props 미전달 콘솔 에러 처리
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/common/CustomToastContainer.tsx
  src/components/input/Input.tsx
  src/pages/login.tsx
Labels: Fix, Refector

#178 [Fix, Refactor] 조건문 단축, 배포 에러 fix
  src/components/card/ChangePassword.tsx
  src/components/input/Input.tsx
Labels: Fix, Refector

#180 [Style] edit: 태블릿, 모바일에서 구성원, 초대 내역 텍스트 이탈 문제 수정
  src/components/table/InviteRecords.tsx
  src/components/table/TablePagination.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
Labels: Style

#183 Update README.md
  README.md
Labels: Docs

#185 [Refactor, Style] mydashboard: 카드 간 여백 조정 / SideMenu: 상하 스크롤 제거, 제목 말줄임표 적용, 페이지 버튼 밀림 현상 수정 / 전체: 배경색 변경
  src/components/button/CardButton.tsx
  src/components/button/DashboardAddButton.tsx
  src/components/columnCard/Column.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/sideMenu/SideMenu.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/styles/globals.css
Labels: Style, Refector

#186 [Refactor, Style] DropdownMenu: 재 클릭 시 닫힘 / Column: 여백, 반응형 조정 / Card: 긴 제목 생략 모바일에도 적용
  src/components/button/CardButton.tsx
  src/components/button/ColumnsButton.tsx
  src/components/button/TodoButton.tsx
  src/components/columnCard/Card.tsx
  src/components/columnCard/CardList.tsx
  src/components/columnCard/Column.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/MemberListMenu.tsx
  src/components/input/Input.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: Style, Refector

#187 [Refactor, Style] mypage, edit: 뒤로가기 버튼 분리, 여백 통일 / landing: 반응형 디자인 일부 수정
  src/components/button/BackButton.tsx
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/landing/LandingMain.tsx
  src/components/landing/Section1.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
Labels: Style, Refector

#188 [Refactor, Style] Zustand 전역 상태 관리에 유저 정보 추가 / mypage: 프로필 변경 즉시 반영
  src/api/users.ts
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/mypage.tsx
  src/store/useUserStore.ts
Labels: Style, Refector

#189 [Fix] mypage: api 요청 무한 루프 에러 수정
  src/components/card/ChangePassword.tsx
  src/pages/mypage.tsx
Labels: Fix

#190 [Refactor] 불필요한 코드 제거
  src/pages/mypage.tsx
Labels: Refector

#191 [Feat, Refector] D&D 적용 및 파일수정
  package-lock.json
  package.json
  src/components/button/CardButton.tsx
  src/components/button/SortableCardButton.tsx
  src/pages/mydashboard.tsx
Labels: Feat, Refector

#192 [Feat] Column D&D 적용
  src/components/columnCard/CardList.tsx
  src/components/columnCard/SortableCard.tsx
Labels: Feat

#193 [Fix, Refactor] edit, mydashboard: 페이지 변경사항 즉시 반영 / edit_MemberList: 멤버 삭제 시 다른 멤버가 삭제되는 버그 fix
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/DeleteDashboardModal.tsx
  src/components/modal/DeleteMemberModal.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
Labels: Fix, Refector

#195 [Refactor] Column, Card: 칼럼 삭제, 카드 생성, 삭제, 수정 즉시 반영 / 마감일 빠른 순 정렬
  src/components/columnCard/CardList.tsx
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/CardInput.tsx
  src/components/modalInput/ToDoModal.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Refector

#196 [Refactor, Fix] Card: 글자수 제한 에러 수정 & text size 반응형 적용
  src/api/card.ts
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/columnCard/CardList.tsx
  src/components/columnCard/Column.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/InputClassNames.ts
  src/components/modalInput/ModalImage.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/ModalTextarea.tsx
  src/components/modalInput/StatusSelect.tsx
  src/components/modalInput/TaskModal.tsx
  src/components/modalInput/ToDoModal.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/member/MemberList.tsx
Labels: Fix, Refector

#197 [Style, Refactor] Column: 카드리스트 스크롤 칼럼으로 이동 / Card: 반응형 디자인 수정
  src/components/button/TodoButton.tsx
  src/components/columnCard/Card.tsx
  src/components/columnCard/CardList.tsx
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/StatusSelect.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
  src/styles/globals.css
Labels: Style, Refector

#198 [Fix] 랜딩페이지 정렬 수정
  src/components/landing/LandingMain.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
Labels: Fix, Style

#199 [Style, Refactor] edit: 내부 컴포넌트 정렬 통일 / NewDashboard: 대시보드 이름 30자 제한 / InviteRecords: 초대 내역 즉시 반영
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modal/NewDashboard.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/TablePagination.tsx
  src/components/table/member/MemberList.tsx
  src/components/table/member/RandomProfile.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: Style, Refector

#200 [fix, Refector] 사이드 메뉴 정렬 및 로고 변경, 칼럼상세 D&D삭제
  src/components/columnCard/CardList.tsx
  src/components/sideMenu/SideMenu.tsx
Labels: Fix, Style, Refector

#201 [Fix, Style, Refector] 사이드 메뉴 CSS 변경, MyDashboardPage에서 새로운 대시보드 생성 시 누락 해결
  src/components/input/Input.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/mydashboard.tsx
  src/pages/signup.tsx
Labels: Fix, Style, Refector

#202 [Style, Refactor] CardDetailModal: 전체적인 CSS 수정과 반응형 작업 / edit: 프로필 이미지 없이도 닉네임 변경
  src/components/card/Profile.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/CommentList.tsx
  src/components/modalDashboard/ProfileIcon.tsx
  src/components/modalDashboard/Representative.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/components/modalInput/CardInput.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/StatusSelect.tsx
  src/components/modalInput/chips/ColorTagChip.tsx
  src/components/modalInput/chips/ColumnNameTag.tsx
  src/types/users.ts
Labels: Style, Refector

#203 [Chore] 불필요해진 코드 제거
  src/components/modalInput/CardInput.tsx
Labels: Chore

#204 [Feat, Rafactor] CardDetailModal: 이미지 클릭 시 팝업 오픈 / ModalInput: tag 개수 4개 제한 & 백스페이스 삭제 기능 추가
  src/components/columnCard/Card.tsx
  src/components/columnCard/Column.tsx
  src/components/modal/DeleteMemberModal.tsx
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/PopupImageModal.tsx
  src/components/modalDashboard/ProfileIcon.tsx
  src/components/modalDashboard/Representative.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/chips/ColorTagChip.tsx
  src/components/modalInput/chips/ColumnNameTag.tsx
  src/components/table/member/RandomProfile.tsx
  src/hooks/useClosePopup.tsx
Labels: Style, Feat, Refector

#206 [Feat Fix Refector] 담당자 선택 갱신 수정
  src/api/card.ts
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/TaskModal.tsx
Labels: Fix, Feat, Refector

#207 [Style, Refactor] CardDetail: 태그 영역 하단 이동 / dashboardindex: 칼럼 추가 버튼 반응형 출력 변경, 헤더&사이드메뉴 고정
  src/components/modalDashboard/CardDetail.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/CommentList.tsx
  src/components/modalDashboard/Representative.tsx
  src/components/modalInput/CardInput.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style, Refector

#208 [Refector Style] 마감일 달력 팝업 CSS 커스텀
  src/components/modalInput/ModalInput.tsx
  src/styles/globals.css
Labels: Style, Refector

#212 [Refactor] 사파리 대응 세로스크롤 방지 목적 window innerHeight 기준 높이 계산식 추가
  src/components/Layouts/DashboardLayout.tsx
  src/components/button/GuestModeButton.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/login.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/pages/signup.tsx
Labels: Refector

#211 [Feat] MyDashboard페이지 D&D 위치변경 저장
  package-lock.json
  package.json
  src/lib/dashboardOrderDB.ts
  src/pages/mydashboard.tsx
Labels: Feat

#214 [Refactor, Style] TaskModal: 마감일 필수 설정 제거 / Card: 카드&댓글 삭제 확인 모달 추가, 제목&내용 공백 검사
  src/api/card.ts
  src/components/button/PaginationButton.tsx
  src/components/columnCard/Card.tsx
  src/components/columnCard/Column.tsx
  src/components/modal/DeleteCheckModal.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/Representative.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/components/modalInput/TaskModal.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
Labels: Style, Refector

#215 [Refector] 컴포넌트 로직분리
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/TaskModal.tsx
  src/components/sideMenu/DashboardItem.tsx
  src/components/sideMenu/SideMenu.tsx
  src/hooks/useCardDetail.ts
  src/hooks/useCardDetailState.ts
  src/hooks/useColumnStatus.ts
  src/hooks/usePagination.ts
  src/hooks/useTaskForm.ts
  src/lib/dashboardUtils.ts
  src/lib/useDashboardDragHandler.ts
  src/pages/mydashboard.tsx
Labels: Refactor

#217 [Fix] 담당자 랜덤 프로필 복구
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/TaskModal.tsx
Labels: Fix

#218 [Fix, Refactor, Style] 전체: post 요청 중복 방지 / CommentList: 카드 담당자=댓글 작성자일 때만 수정/삭제되던 버그 fix
  src/api/members.ts
  src/components/modal/DeleteDashboardModal.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/NewDashboard.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/CommentList.tsx
  src/components/modalDashboard/Representative.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/TaskModal.tsx
  src/hooks/usePostGuard.ts
  src/hooks/useTaskForm.ts
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: Fix, Style, Refactor

#219 [Refactor] FormModal, TaskModal: 모바일 확대 방지 input text 최소 size 16px 변경
  src/components/modal/FormModal.tsx
  src/components/modal/NewDashboard.tsx
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/InputClassNames.ts
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/ModalTextarea.tsx
  src/components/modalInput/StatusSelect.tsx
  src/components/modalInput/TaskModal.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Refactor

#220 [Fix] 카드, 칼럼 상태 변경오류 해결
  src/api/columns.ts
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/components/modalDashboard/formatDate.ts
  src/components/modalInput/CardInput.tsx
  src/components/modalInput/ModalImage.tsx
  src/components/modalInput/ModalTextarea.tsx
  src/components/modalInput/TaskModal.tsx
  src/components/modalInput/TextButton.tsx
  src/hooks/useCardDetailState.ts
  src/hooks/useColumnStatus.ts
  src/hooks/useTaskForm.ts
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Fix

#221 [Fix, Style] TaskModal: 분리 전으로 롤백 / Landing: 버튼 너비 반응형 적용 / Card: 컨테이너 높이 반응형 적용
  src/api/members.ts
  src/components/button/GuestModeButton.tsx
  src/components/columnCard/Card.tsx
  src/components/landing/Section1.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalInput/chips/TagColorChip.tsx
Labels: Fix, Style

#222 [Fix] TaskModal: 분리 전으로 롤백
  src/api/columns.ts
  src/components/columnCard/Column.tsx
  src/components/modalDashboard/CardDetailModal.tsx
  src/components/modalDashboard/UpdateComment.tsx
  src/components/modalDashboard/formatDate.ts
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/CardInput.tsx
  src/components/modalInput/ModalImage.tsx
  src/components/modalInput/ModalTextarea.tsx
  src/components/modalInput/TaskModal.tsx
  src/components/modalInput/TextButton.tsx
  src/hooks/useCardDetailState.ts
  src/hooks/useColumnStatus.ts
  src/hooks/useTaskForm.ts
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Fix

#224 [Refactor] mypage: 비밀번호 경고 메시지 중복 표시 fix / Landing: 버튼 너비 조절
  src/components/card/ChangePassword.tsx
  src/components/landing/Section1.tsx
Labels: Refactor

#225 [Fix, Refactor] signup: 중복 이메일 가입 에러 토스트 처리 / InvitedDashboard: 컴포넌트 깜빡임 fix
  src/components/gnb/MemberListMenu.tsx
  src/components/gnb/UserMenu.tsx
  src/components/landing/Section1.tsx
  src/components/modalInput/chips/SelectTagColorChip.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/signup.tsx
Labels: Fix, Style, Refactor

#229 [Docs] Update README.md
  README.md
Labels: Docs
