Repository part3-4team-Taskify/Taskify, pull requests merged in 2025-03, with the labels that each got.

#28 [Feat] 공통 폰트 & 컬러 스타일 정의
  .github/workflows/main.yml
  declares.d.ts
  postcss.config.mjs
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Style

#31 [Fix] 공통 color중 text color @layer utilities로 정의
  src/styles/globals.css
Labels: Fix, Style

#34 [Docs] Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#35 [feat] input, side-menu, modal-yk
  package-lock.json
  package.json
  public/svgs/logo-large.svg
  public/svgs/logo.svg
  public/svgs/logo_taskify.svg
  src/components/ModalInput/AddButton.tsx
  src/components/ModalInput/InputClassNames.ts
  src/components/ModalInput/ModalImage.tsx
  src/components/ModalInput/ModalInput.tsx
  src/components/ModalInput/ModalTextarea.tsx
  src/components/ModalInput/TextButton.tsx
  src/components/ModalInput/ToDoModal.tsx
  src/components/ModalInput/chips/ColorTagChip.tsx
  src/components/SideMenu/ComminLayout.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/dashboard.ts
  src/components/button/CardButton.tsx
  src/components/button/ColumnsButton.tsx
  src/components/button/DashboardAddButton.tsx
  src/components/button/DashboardDeleteButton.tsx
  src/components/button/TodoButton.tsx
  src/components/input/Input.tsx
  src/pages/api/axiosInstance.ts
  src/pages/index.tsx
Labels: Feat

#39 [Feat] Header 컴포넌트 작업 (내부 버튼 활성화 완료, api는 멤버 목록 불러오기까지만 적용)
  public/svgs/add-box.svg
  public/svgs/dummy-icon.png
  public/svgs/logo-large-white.svg
  public/svgs/logo-large.svg
  public/svgs/logo-small-white.svg
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderDashboard.tsx
  src/components/Gnb/HeaderDefault.tsx
  src/components/Gnb/HeaderDefaultBk.tsx
  src/components/Gnb/HeaderMypage.tsx
  src/pages/_document.tsx
Labels: Feat

#40 [Fix] Header 컴포넌트 스크롤바 밀림 이슈 해결 & RandomProfile 컴포넌트 연동
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderDashboard.tsx
  src/components/Gnb/HeaderMypage.tsx
  src/components/Gnb/ModalInviting.tsx
  src/components/Gnb/members.ts
  src/pages/api/members.ts
  src/styles/globals.css
Labels: Fix

#42 [Feat] 404 Not Found 에러 페이지 제작
  src/pages/404.tsx
Labels: Feat

#43 [Feat] signup 페이지 디자인
  src/pages/signup.tsx
Labels: Feat

#44 [Feat] Modal : 비브리지 변경, 새로운 대시보드 / Pages : 대시보드 상세, 수정 페이지
  .gitignore
  src/components/SideMenu/ComminLayout.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/button/CustomBtn.tsx
  src/components/button/PaginationBtn.tsx
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/input/Input.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/NewDashboard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/pages/test.tsx
Labels: Feat

#45 [Feat] mypage 생성
  src/pages/mypage.tsx
Labels: Feat

#46 [Feat] Card: 대시보드 카드 / Page: 대시보드 페이지
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  next.config.ts
  public/svgs/img.svg
  src/components/ColumnCard/Card.tsx
  src/components/ColumnCard/Column.tsx
  src/pages/api/axiosInstance.ts
  src/pages/api/dashboard.ts
  src/pages/dashboards.tsx
  src/types/task.ts
Labels: Feat

#48 [Feat] Modal: 공통 컴포넌트 모달
  src/api/axiosInstance.ts
  src/api/dashboard.ts
  src/api/hello.ts
  src/api/members.ts
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderMypage.tsx
  src/components/common/Modal/Modal.tsx
  src/pages/dashboards.tsx
Labels: Feat

#51 [Feat] 랜딩 페이지 추가
  src/components/landing/Footer.tsx
  src/components/landing/LandingMain.tsx
  src/components/landing/Section1.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
  src/pages/index.tsx
Labels: Feat

#52 [Feat] Login 페이지 추가
  src/pages/login.tsx
Labels: Feat

#53 [Feat] 인풋 추가 수정
  src/components/ModalInput/ModalInput.tsx
  src/components/input/Input.tsx
Labels: Fix, Feat

#54 [Fix] Header: 랜덤프로필 컴포넌트 더미 데이터 연결 & 이미지 절대경로로 수정
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderDashboard.tsx
  src/components/Gnb/HeaderDefault.tsx
  src/components/Gnb/HeaderDefaultBk.tsx
  src/components/Gnb/HeaderMypage.tsx
Labels: Fix

#55 [Refector, Fix] Page: 대시보드 페이지 타입 정의 및 통합
  src/components/ColumnCard/Card.tsx
  src/components/ColumnCard/Column.tsx
  src/pages/dashboard.tsx
  src/types/task.ts
Labels: Fix, Refector

#56 [Fix] Vercel 오류 해결
  src/components/ModalInput/AssigneeSelect.tsx
  src/components/ModalInput/ModalTextarea.tsx
  src/components/SideMenu/ComminLayout.tsx
  src/components/SideMenu/SideMenu.tsx
  src/pages/mydashboards.tsx
Labels: Fix, Refector

#57 [Fix] 배포 Build 에러 해결을 위한 파일 수정
  src/components/ColumnCard/Column.tsx
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderDashboard.tsx
  src/components/Gnb/HeaderMypage.tsx
  src/components/card/ChangePassword.tsx
  src/components/card/Profile.tsx
  src/components/modal/NewDashboard.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/mypage.tsx
Labels: Fix

#59 [Fix] login: 배포 에러 해결 목적의 파일 수정
  src/pages/login.tsx
Labels: Fix

#60 [Fix] Card, Column Type에러 수정
  src/components/ColumnCard/Card.tsx
  src/components/ColumnCard/Column.tsx
Labels: Fix

#62 [Fix] Gnb: 배포 에러 해결 목적의 파일 수정
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderMypage.tsx
Labels: Fix

#63 [Fix]마이페이지 사이드메뉴 경로수정
  src/api/apiRoutes.ts
  src/pages/mypage.tsx
Labels: Fix

#65 [Feat] Create build.sh
  build.sh
Labels: Feat

#66 [Feat] Create deploy.yml
  .github/workflows/deploy.yml
Labels: Feat

#67 [Fix] vercel, git actions 배포: Update deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#69 [Fix] vercel, git actions 배포: Update deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#73 [Fix] vercel, git actions 배포: Create deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#74 [Fix] vercel, git actions 배포: Update deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#72 [Style] Modal: 스타일 변경
  src/components/common/Modal/Modal.tsx
Labels: Style

#75 [Fix] vercel, git actions 배포: Update deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#76 [Fix] vercel, git actions 배포: Update build.sh
  build.sh
Labels: Fix

#78 [Refactor] Gnb: 헤더 비브리지, 대시보드, 마이페이지 컴포넌트에 user info api 연동
  src/api/members.ts
  src/api/user.ts
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderDashboard.tsx
  src/components/Gnb/HeaderMypage.tsx
  src/components/Gnb/ModalInviting.tsx
  src/components/Gnb/type.ts
  src/components/table/member/MemberList.tsx
Labels: Refector

#80 [Feat] 나의 대쉬보드 페이지 작성
  src/components/input/Input.tsx
  src/pages/mydashboard.tsx
Labels: Fix, Feat

#81 [Feat] Gnb: 헤더 내부 api 로딩에 스켈레톤 UI 적용
  src/components/Gnb/HeaderBebridge.tsx
  src/components/Gnb/HeaderDashboard.tsx
  src/components/Gnb/HeaderMypage.tsx
  src/components/Gnb/skeletonUser.tsx
Labels: Feat

#82 [Feat] 404: 시간 경과 시 홈페이지 이동 기능, 홈페이지 이동하기 버튼 추가
  src/pages/404.tsx
Labels: Feat

#83 [Feat] 사이드 메뉴 Api연결
  src/api/axiosInstance.ts
  src/api/sidemenu.ts
  src/components/SideMenu/SideMenu.tsx
  src/pages/mydashboard.tsx
Labels: Feat

#87 [Feat] 나의 대쉬보드 페이지
  src/components/button/CardButton.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/mydashboard.tsx
Labels: Fix, Feat

#88 [Feat] Page: 대시보드 상세페이지 UI
  src/components/columnCard/Column.tsx
  src/components/modal/Modal.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboards.tsx
Labels: Feat

#89 [Feat] Page: 대시보드 수정 페이지 / Moal : 초대하기
  public/svgs/close-white.svg
  src/api/apiRoutes.ts
  src/api/members.ts
  src/components/gnb/HeaderBebridge.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modal/NewDashboard.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboards.tsx
  src/pages/mypage.tsx
  src/pages/test.tsx
  src/types/users.ts
Labels: Feat

#91 [Feat, Refactor] login: 로그인 요청, token 저장 기능 추가 / 공통 상수 폴더 추가
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/api/members.ts
  src/api/user.ts
  src/constants/team.ts
  src/pages/login.tsx
  src/store/useUserStore.ts
Labels: Feat, Refector

#93 [Refactor, Feat] Gnb: 헤더 컴포넌트 병합, 스타일 공통화 / 대시보드 타이틀 api 연동
  src/api/dashboards.ts
  src/components/gnb/HeaderBebridge.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/HeaderDefault.tsx
  src/components/gnb/HeaderDefaultBk.tsx
  src/components/gnb/HeaderMypage.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
Labels: Feat, Refector

#95 [Feat] Page: 대시보드 페이지 / Modal: 새 칼럼 생성, 칼럼 관리(삭제, 변경)
  public/svgs/dummy-icon.png
  src/api/dashboards.ts
  src/components/button/CustomButton.tsx
  src/components/button/PaginationButton.tsx
  src/components/columnCard/AddColumnModal.tsx
  src/components/columnCard/Column.tsx
  src/components/columnCard/ColumnDeleteModal.tsx
  src/components/columnCard/ColumnManageModal.tsx
  src/components/modal/Modal.tsx
  src/pages/dashboard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/types/task.ts
Labels: Feat

#96 [Refactor, Feat] Gnb: 헤더 기본 출력 기능 추가
  src/components/Layouts/DashboardLayout.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/types/dashboard.ts
Labels: Feat, Refector

#97 [Feat] Gnb: 유저 정보 섹션 클릭 시 mypage 이동 기능 추가
  src/components/gnb/HeaderDashboard.tsx
  src/components/modal/MypageModal.tsx
Labels: Feat

#98 [Feat] 할일 생성모달 Api 연결
  src/api/axiosInstance.ts
  src/api/card.ts
  src/components/columnCard/Column.tsx
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/ModalImage.tsx
  src/components/modalInput/ModalInput.tsx
  src/components/modalInput/ToDoModal.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
Labels: Fix, Feat

#99 [Feat] Moadal : 초대받은 대시보드
  src/api/apiRoutes.ts
  src/api/axiosInstance.ts
  src/api/user.ts
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/modal/NewDashboard.tsx
  src/components/table/invited/EmptyInvitations.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mypage.tsx
  src/pages/test.tsx
  src/types/invite.ts
Labels: Feat

#101 [feat] 할일 수정모달 api연결
  src/api/card.ts
  src/components/modalInput/ModalImage.tsx
  src/components/modalInput/TaskModal.tsx
Labels: Feat

#100 [Feat, Refactor] Gnb: 드롭다운 메뉴 추가, 멤버 목록 아이콘 수정
  package-lock.json
  package.json
  public/svgs/dummy-icon.png
  src/components/gnb/Avatars.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/HeaderDefault.tsx
  src/components/gnb/UserMenu.tsx
  src/components/table/member/RandomProfile.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Feat, Refector

#102 [Feat] 사이드 메뉴 및 모달 css 변경
  src/api/dashboards.ts
  src/components/modalInput/TaskModal.tsx
  src/components/modalInput/ToDoModal.tsx
  src/components/sideMenu/ComminLayout.tsx
  src/components/sideMenu/SideMenu.tsx
  src/components/sideMenu/dashboard.ts
Labels: Fix, Feat

#103 [Fix] Gnb: 멤버 목록 프로필 이미지 출력 오류 디버깅, 정원형 출력을 위한 리팩토링
  src/components/gnb/Avatars.tsx
  src/components/table/member/RandomProfile.tsx
  src/pages/dashboard.tsx
Labels: Fix

#105 [Feat, Refactor] Gnb: 드롭다운 메뉴 'MemberListMenu' 추가 / hooks: 공통 훅 useClosePopup 추가
  src/components/gnb/Avatars.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/MemberListMenu.tsx
  src/components/gnb/UserMenu.tsx
  src/components/table/member/RandomProfile.tsx
  src/hooks/useClosePopup.tsx
Labels: Feat, Refector

#104 [Feat, Style] Column, Card: UI 개선 및 기능 추가
  src/api/axiosInstance.ts
  src/api/dashboards.ts
  src/components/columnCard/Card.tsx
  src/components/columnCard/Column.tsx
  src/components/columnCard/ColumnManageModal.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style

#106 [Feat, Refactor, Fix] Login: 비로그인 상태에서 페이지 접근 시 /login 이동
  src/api/apiRoutes.ts
  src/api/auth.ts
  src/api/axiosInstance.ts
  src/api/users.ts
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/HeaderDefault.tsx
  src/components/gnb/UserMenu.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/hooks/useAuthGuard.ts
  src/hooks/useClosePopup.tsx
  src/pages/_app.tsx
  src/pages/login.tsx
  src/pages/mydashboard.tsx
  src/store/useUserStore.ts
  src/utils/parseJwt.ts
Labels: Fix, Feat, Refector

#107 [Feat] signup: 회원가입 post 요청 연결 / 성공 시 login 페이지 이동
  src/api/users.ts
  src/pages/signup.tsx
Labels: Feat

#108 [Refactor] alret > toast 변경 / 관리 버튼 권한 추가
  package-lock.json
  package.json
  src/api/members.ts
  src/components/gnb/HeaderDashboard.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/InviteDashboard.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/InvitedDashBoard.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/styles/globals.css
Labels: Refector

#109 [Feat, Style, Refactor] 비로그인 상태에서 페이지 접근 시 화면 깜빡임 현상 수정, 로딩 스피너 추가
  src/components/common/LoadingSpinner.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/MemberListMenu.tsx
  src/components/gnb/UserMenu.tsx
  src/hooks/useAuthGuard.ts
  src/pages/_app.tsx
  src/pages/mydashboard.tsx
Labels: Style, Feat, Refector

#110 [Refactor] 로그인 토큰 만료 설정 제거(백엔드 설정 없음)
  src/api/auth.ts
  src/api/axiosInstance.ts
  src/components/gnb/HeaderDefault.tsx
  src/components/gnb/UserMenu.tsx
  src/hooks/useAuthGuard.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/utils/parseJwt.ts
Labels: Refector

#111 [Fix, Refactor] Page : edit 프로필 이미지 수정 / Modal : 초대내역 : 디자인, 페이지네이션 수정
  src/components/columnCard/Column.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/table/InviteRecords.tsx
  src/components/table/invited/EmptyInvitations.tsx
  src/components/table/member/MemberList.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/test.tsx
Labels: Fix, Refector

#112 [Feat Fix] CSS 수정 및 사이드 메뉴 기능추가
  src/api/dashboards.ts
  src/components/modal/NewDashboard.tsx
  src/components/modalInput/AssigneeSelect.tsx
  src/components/modalInput/StatusSelect.tsx
  src/components/modalInput/TaskModal.tsx
  src/components/modalInput/ToDoModal.tsx
  src/components/sideMenu/SideMenu.tsx
  src/pages/mydashboard.tsx
Labels: Fix, Feat

#113 [Feat] 사이드메뉴 접기/펴기
  src/components/sideMenu/SideMenu.tsx
Labels: Feat

#114 [Refector] Modal: hover 효과 / Colum : 반응형
  src/components/columnCard/AddColumnModal.tsx
  src/components/columnCard/ColumnDeleteModal.tsx
  src/components/columnCard/ColumnManageModal.tsx
  src/components/modal/ChangeBebridge.tsx
  src/components/modal/NewDashboard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Refector

#116 Update README.md
  README.md
Labels: Docs

#119 [Feat, Style] mydashboard: 관리 모드 추가 / CardButton: 대시보드 탈퇴 기능 추가
  src/components/button/CardButton.tsx
  src/components/button/DashboardAddButton.tsx
  src/components/button/PaginationButton.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/components/gnb/HeaderDefault.tsx
  src/components/gnb/MemberListMenu.tsx
  src/components/gnb/UserMenu.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/mydashboard.tsx
Labels: Style, Feat

#120 [Style] Card: 반응형 / Dashboard Page: 반응형
  package-lock.json
  package.json
  src/components/button/ColumnsButton.tsx
  src/components/button/TodoButton.tsx
  src/components/columnCard/Card.tsx
  src/components/columnCard/Column.tsx
  src/components/modal/NewDashboard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style

#122 [Refactor, Style] Gnb: 헤더 종류 추가, 관리 모드 버튼 스타일 수정
  src/components/gnb/Avatars.tsx
  src/components/gnb/HeaderDashboard.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
Labels: Style, Refector
